### PR TITLE
Update Fluorescent with recent changes

### PR DESCRIPTION
**Pull request by ksiazkowicz**

### CODE REVIEW

**Comment by bhavin192** [comment]
Are you going to keep both projects in one ?? I thought you will keep both separate and update git repo and call in fluorescent ?

**Comment by ksiazkowicz** [comment]
Both are to be kept separate. I just want to have this branch updated with the changes from main.

**Comment by bhavin192** [comment]
so lightbulb will have different repo and fluorescent will have different repo

**Comment by ksiazkowicz** [comment]
Well, it can't be done in any other way, right? :> The first merge is harder cause it wants to merge also the parts that revert changes done in 0.4. As I sort these conflicts out, next ones should be easier to perform.

**Comment by bhavin192** [comment]
yup that's the easy way 
or you to use #define fluorescent 

and use #ifdef in all changes rather than lightbulb and have to keep both code in one file 

it will be more complex because everytime you make large coding

**Comment by ksiazkowicz** [comment]
This "define" thing would make sense if I'm ever going to finish my Sailfish port and try to make this thing multiplatform. But here - it just makes no sense at all. Using branches is a more clean and natural way.

**Comment by bhavin192** [comment]
do you test it in VM

**Comment by ksiazkowicz** [comment]
Well, I just managed to build it and then I realized I'd have to code the UI from scratch so I dropped it. It wasn't touched since like 3 months anyway.

**Comment by ksiazkowicz** [comment]
Done.

**Pull request closed without merging**
